"""Annual commissioning calculations mechanically extracted from the legacy page.

Generated by scripts/extract_annual_calculations.py; verify against original
page execution after updating. Zero filling and historical overrides are the
legacy rules, not additional claims of source completeness.
"""
import pandas as pd
from pipeline.data_access import monitoring_by_year, month_label, quarter_label
from pipeline.report_values import records

COLORS = {"green": "#2c9869", "amber": "#d6a23f", "blue": "#398dcc", "teal": "#329d9c"}

TITLES = {"b1": "Ввод недвижимости", "b2_1": "МКД и ИЖС",
          "b2_2": "Бюджетное и небюджетное жильё · Москва", "b2_3": "Реновация · Москва",
          "b3_1": "Нежильё и нежилые помещения в жилье · Москва",
          "b3_2": "Бюджетное и небюджетное нежильё · Москва", "b3_3": "Нежильё по отраслям · Москва"}

def append_chart(charts, frame, series, *, year_from, year_to, key, totals=True, height=360):
    years = list(range(year_from, year_to + 1))
    if frame is None or frame.empty:
        shown = pd.DataFrame({"year": years})
    else:
        shown = frame.set_index("year").reindex(years).reset_index()
    for column, _, _ in series:
        if column not in shown.columns:
            shown[column] = 0.0
    shown = shown.fillna(0.0)
    columns = ["year"] + [column for column, _, _ in series]
    charts.append({"id": key, "title": TITLES[key], "unit": "млн м²", "totals": totals,
                   "columns": [{"id": "year", "label": "Год"}] + [{"id": col, "label": label} for col, label, _ in series],
                   "rows": records(shown[columns]),
                   "series": [{"id": col, "name": label, "color": color,
                               "points": [{"x": str(int(row["year"])), "y": row[col]} for row in records(shown[columns])]}
                              for col, label, color in series],
                   "summaries": [{"from": year_from, "to": end,
                                  "values": [{"id": col, "label": label, "value": _sum_range(frame, col, year_from, end)}
                                             for col, label, _ in series]}
                                 for end in (2025, 2026)]})

C_ZH = COLORS['green']
C_NZH = '#7B8794'
C_IZHS = COLORS['amber']
C_NEBUDG = '#6743A7'
C_BUDG = COLORS['blue']
C_NZH_IN = COLORS['teal']
C_MOP = COLORS['amber']
BRANCH_COLORS = ['#2459A6', '#18864B', '#A45A00', '#A63876', '#6743A7', '#087E8B', '#B14730', '#5A748A', '#697586']
BRANCH_LABELS = {'офисы': 'Офисы', 'соц': 'Социальные объекты', 'пром': 'Промышленные', 'гостиницы': 'Гостиницы', 'торговля': 'Торговля', 'транспорт': 'Транспорт', 'склады': 'Склады', 'жкх': 'ЖКХ'}
RENOVATION_VALUES = {2017: 0.3, 2018: 0.2, 2019: 0.2, 2020: 0.4, 2021: 1.2, 2022: 0.8, 2023: 1.2, 2024: 1.3, 2025: 2.3}
MOP_VALUES = {2011: 1.2, 2012: 1.3, 2013: 1.8, 2014: 1.4, 2015: 1.8, 2016: 1.7, 2017: 2.1, 2018: 2.3, 2019: 3.3, 2020: 3.2, 2021: 4.7, 2022: 3.9, 2023: 4.5, 2024: 4.1, 2025: 4.9}

def ru_num(value, digits=1):
    if value is None or pd.isna(value):
        return '—'
    try:
        s = f'{float(value):,.{digits}f}'
    except (TypeError, ValueError):
        return str(value)
    return s.replace(',', ' ').replace('.', ',')

def _emiss_delta_from_ytd(df: pd.DataFrame, months: list[int]) -> pd.DataFrame:
    src = df[df['month'].isin(months)].copy()
    if src.empty:
        return src
    rows = []
    for _, g in src.sort_values(['year', 'month']).groupby('year'):
        prev = {'МКД': 0.0, 'ИЖС': 0.0}
        for _, row in g.iterrows():
            new = row.copy()
            for col in ('МКД', 'ИЖС'):
                value = float(row.get(col, 0) or 0)
                new[col] = max(value - prev[col], 0.0)
                prev[col] = value
            rows.append(new)
    return pd.DataFrame(rows)

def _emiss_annual_for_region(df: pd.DataFrame, region: str) -> pd.DataFrame:
    if df is None or df.empty or 'region' not in df.columns:
        return pd.DataFrame(columns=['year', 'МКД', 'ИЖС'])
    sub = df[(df['region'] == region) & df['period_type'].isin(['year', 'ytd']) & (df['month'] == 12)].copy()
    if sub.empty:
        return pd.DataFrame(columns=['year', 'МКД', 'ИЖС'])
    return sub.sort_values(['year', 'source_file']).drop_duplicates('year', keep='last')[['year', 'МКД', 'ИЖС']].sort_values('year').reset_index(drop=True)

def _sum_range(df: pd.DataFrame, col: str, y0: int, y1: int) -> float:
    if df is None or df.empty or col not in df.columns:
        return 0.0
    m = (df['year'] >= y0) & (df['year'] <= y1)
    return float(pd.to_numeric(df.loc[m, col], errors='coerce').fillna(0).sum())

def _upsert_year(df: pd.DataFrame, row: dict) -> pd.DataFrame:
    row_df = pd.DataFrame([row])
    if df is None or df.empty:
        return row_df
    return pd.concat([df, row_df], ignore_index=True).drop_duplicates(subset=['year'], keep='last')

def _budget_split_with_2026(static_df: pd.DataFrame, live_2026: pd.DataFrame) -> pd.DataFrame:
    cols = ['year', 'Небюджет', 'Бюджет']
    base = pd.DataFrame(columns=cols)
    if static_df is not None and (not static_df.empty):
        base = static_df[static_df['year'].between(2011, 2025)].copy()
        base = base[[c for c in cols if c in base.columns]]
    if live_2026 is not None and (not live_2026.empty):
        base = pd.concat([base, live_2026[cols]], ignore_index=True)
    return base.drop_duplicates(subset=['year'], keep='last').sort_values('year')

def _monitoring_mop_row(rv: pd.DataFrame, year: int) -> dict | None:
    required = {'Год ввода по Мосстату', 'category_моп'}
    if rv is None or rv.empty or (not required.issubset(set(rv.columns))):
        return None
    part = rv[pd.to_numeric(rv['Год ввода по Мосстату'], errors='coerce') == year]
    if part.empty:
        return None
    value = float(pd.to_numeric(part['category_моп'], errors='coerce').fillna(0).sum()) / 1000000.0
    return {'year': year, 'МОП': value} if value > 0 else None

def _monitoring_nonres_row(rv: pd.DataFrame, year: int) -> dict | None:
    required = {'Год ввода по Мосстату', 'category_нежилое_отдельное', 'category_нежилое_в_жилом'}
    if rv is None or rv.empty or (not required.issubset(set(rv.columns))):
        return None
    part = rv[pd.to_numeric(rv['Год ввода по Мосстату'], errors='coerce') == year]
    if part.empty:
        return None
    standalone = float(pd.to_numeric(part['category_нежилое_отдельное'], errors='coerce').fillna(0).sum()) / 1000000.0
    in_housing = float(pd.to_numeric(part['category_нежилое_в_жилом'], errors='coerce').fillna(0).sum()) / 1000000.0
    if standalone == 0 and in_housing == 0:
        return None
    return {'year': year, 'нежильё': standalone, 'нежилые_в_жилье': in_housing, 'общая': standalone + in_housing}

def _monitoring_nonres_branch_row(rv: pd.DataFrame, year: int) -> dict | None:
    nonres = _monitoring_nonres_row(rv, year)
    if not nonres or rv is None or rv.empty or ('Отрасли' not in rv.columns):
        return None
    part = rv[pd.to_numeric(rv['Год ввода по Мосстату'], errors='coerce') == year].copy()
    if 'category_нежилое_отдельное' not in part.columns:
        return None
    area = pd.to_numeric(part['category_нежилое_отдельное'], errors='coerce').fillna(0)
    industries = part['Отрасли'].fillna('').astype(str).str.casefold()

    def matches(*tokens: str):
        mask = pd.Series(False, index=part.index)
        for token in tokens:
            mask |= industries.str.contains(token, regex=False)
        return mask
    masks = {'офисы': matches('административно-деловые'), 'соц': matches('доу', 'школ', 'образователь', 'лечебно', 'спортивно', 'культов', 'культурно', 'социально'), 'пром': matches('производ', 'пром'), 'гостиницы': matches('гостини'), 'торговля': matches('торгов'), 'транспорт': matches('транспорт'), 'склады': matches('склад'), 'жкх': matches('жкх', 'коммуналь')}
    assigned = pd.Series(False, index=part.index)
    result = {'year': year}
    for category, mask in masks.items():
        selected = mask & ~assigned
        result[category] = float(area[selected].sum()) / 1000000.0
        assigned |= selected
    return result

def annual_charts(data, region):
    charts = []
    vvod = data['load_vvod_static']
    emiss = data['load_emiss_34118']
    emiss_periods = data['load_emiss_34118_periods']
    mon = data['load_monitoring_2_0']
    monitoring_static = data['load_monitoring_2011_2026_static']
    rv = mon.get('rv', pd.DataFrame())
    if all((v.empty for v in vvod.values())) and emiss.empty:
        return charts
    is_msk = region == 'Москва'
    YF, YT = (2011, 2026)
    if is_msk:
        b1 = vvod['msk_total'][['year', 'жильё']].copy()
        mop = pd.DataFrame([{'year': year, 'МОП': value} for year, value in MOP_VALUES.items()])
        mop26 = _monitoring_mop_row(rv, 2026)
        if mop26:
            mop = _upsert_year(mop, mop26)
        b1 = b1.merge(mop, on='year', how='outer')
        nonres_split = vvod['msk_nonres'][['year', 'нежильё', 'нежилые_в_жилье']].copy()
        b1 = b1.merge(nonres_split, on='year', how='outer')
        zh26 = monitoring_by_year(rv, gruppirovka='Жилье', value_col='Жилая площадь', year_from=2026, year_to=2026)
        v_zh = float(zh26['value'].iloc[0]) if not zh26.empty else float('nan')
        nonres26 = _monitoring_nonres_row(rv, 2026)
        if not pd.isna(v_zh) or nonres26:
            row26 = {'year': 2026, 'жильё': v_zh}
            if nonres26:
                row26.update({'нежильё': nonres26['нежильё'], 'нежилые_в_жилье': nonres26['нежилые_в_жилье']})
            if mop26:
                row26['МОП'] = mop26['МОП']
            b1 = _upsert_year(b1, row26)
    else:
        b1 = vvod['rf_total'][['year', 'жильё', 'нежильё']].copy()
    b1_series = [('жильё', 'Жильё', C_ZH), ('нежильё', 'Нежильё', C_NZH)]
    if is_msk:
        b1_series = [('жильё', 'Жильё', C_ZH), ('МОП', 'МОП', C_MOP), ('нежилые_в_жилье', 'Нежилье в жилье', C_NZH_IN), ('нежильё', 'Нежилье', C_NZH)]
    append_chart(charts, b1, b1_series, year_from=YF, year_to=YT, key='b1', height=320)
    for y0, y1 in [(2011, 2025), (2011, 2026)]:
        zh = _sum_range(b1, 'жильё', y0, y1)
        mop_sum = _sum_range(b1, 'МОП', y0, y1) if is_msk else 0.0
        nzh = _sum_range(b1, 'нежильё', y0, y1)
        nzh_in = _sum_range(b1, 'нежилые_в_жилье', y0, y1) if is_msk else 0.0
        has26 = not is_msk and y1 == 2026
        mop_line = f'- {ru_num(mop_sum)} млн м² МОП\n' if is_msk else ''
        nzh_in_line = f'- {ru_num(nzh_in)} млн м² нежилья в жилье\n' if is_msk else ''
    emiss_region = 'Москва' if is_msk else 'РФ'
    b2_1 = _emiss_annual_for_region(emiss_periods, emiss_region)
    if b2_1.empty:
        b2_1 = vvod['msk_residential'].copy() if is_msk else emiss.copy()
    if not b2_1.empty and {'year', 'ИЖС'}.issubset(b2_1.columns):
        b2_1.loc[pd.to_numeric(b2_1['year'], errors='coerce').lt(2015), 'ИЖС'] = 0.0
    if is_msk:
        mkd26 = monitoring_by_year(rv, gruppirovka='Жилье', value_col='Жилая площадь', year_from=2026, year_to=2026)
        if not mkd26.empty:
            b2_1 = pd.concat([b2_1, pd.DataFrame([{'year': 2026, 'МКД': float(mkd26['value'].iloc[0]), 'ИЖС': 0.0}])], ignore_index=True).drop_duplicates(subset=['year'], keep='last')
    append_chart(charts, b2_1, [('МКД', 'МКД', C_ZH), ('ИЖС', 'ИЖС', C_IZHS)], year_from=YF, year_to=YT, key='b2_1', height=300)
    if is_msk:
        nb = monitoring_by_year(rv, gruppirovka='Жилье', istochnik=['Внебюджет'], value_col='Жилая площадь', year_from=2026, year_to=2026).rename(columns={'value': 'Небюджет'})
        bd = monitoring_by_year(rv, gruppirovka='Жилье', istochnik=['Городской бюджет', 'Федеральный бюджет'], value_col='Жилая площадь', year_from=2026, year_to=2026).rename(columns={'value': 'Бюджет'})
        live_b2_2 = pd.merge(nb, bd, on='year', how='outer')
        b2_2 = _budget_split_with_2026(monitoring_static['residential_budget_split'], live_b2_2)
        append_chart(charts, b2_2, [('Небюджет', 'Небюджет', C_NEBUDG), ('Бюджет', 'Бюджет', C_BUDG)], year_from=YF, year_to=YT, key='b2_2', height=300)
        b2_3 = pd.DataFrame([{'year': year, 'Реновация': value} for year, value in RENOVATION_VALUES.items()])
        if not rv.empty and {'Год ввода по Мосстату', 'Инвестор для Реновации', 'Жилая площадь'}.issubset(rv.columns):
            ren_rows = rv[rv['Инвестор для Реновации'].fillna('').astype(str).str.strip().str.casefold().eq('да')].copy()
            if not ren_rows.empty:
                ren_rows['year'] = pd.to_numeric(ren_rows['Год ввода по Мосстату'], errors='coerce')
                ren_rows['area'] = pd.to_numeric(ren_rows['Жилая площадь'], errors='coerce').fillna(0)
                for year, part in ren_rows.groupby('year'):
                    if 2022 <= year <= YT:
                        b2_3 = _upsert_year(b2_3, {'year': int(year), 'Реновация': float(part['area'].sum()) / 1000000.0})
        append_chart(charts, b2_3, [('Реновация', 'Реновация', C_ZH)], year_from=2017, year_to=YT, key='b2_3', height=280, totals=False)
    if not is_msk:
        return charts
    b3_1 = vvod['msk_nonres'].copy()
    nonres26 = _monitoring_nonres_row(rv, 2026)
    if nonres26:
        b3_1 = _upsert_year(b3_1, nonres26)
    append_chart(charts, b3_1, [('нежильё', 'Нежильё', C_NZH), ('нежилые_в_жилье', 'Нежилые в жилье', C_NZH_IN)], year_from=YF, year_to=YT, key='b3_1', height=300)
    nb3 = monitoring_by_year(rv, istochnik=['Внебюджет'], value_col='category_нежилое_отдельное', year_from=2026, year_to=2026).rename(columns={'value': 'Небюджет'})
    bd3 = monitoring_by_year(rv, istochnik=['Городской бюджет', 'Федеральный бюджет'], value_col='category_нежилое_отдельное', year_from=2026, year_to=2026).rename(columns={'value': 'Бюджет'})
    live_b3_2 = pd.merge(nb3, bd3, on='year', how='outer')
    b3_2 = _budget_split_with_2026(monitoring_static['nonres_budget_split'], live_b3_2)
    append_chart(charts, b3_2, [('Небюджет', 'Небюджет', C_NEBUDG), ('Бюджет', 'Бюджет', C_BUDG)], year_from=YF, year_to=YT, key='b3_2', height=300)
    br = vvod['msk_nonres_branches'].copy()
    for year in range(2017, 2027):
        live_branch = _monitoring_nonres_branch_row(rv, year)
        if not live_branch:
            continue
        static_total = b3_1.loc[b3_1['year'].eq(year), 'нежильё']
        live_total = _monitoring_nonres_row(rv, year)
        if year < 2026 and (static_total.empty or not live_total or live_total['нежильё'] < float(static_total.iloc[0]) * 0.95):
            continue
        br = _upsert_year(br, live_branch)
    if not br.empty:
        tot = b3_1[['year', 'нежильё']] if not b3_1.empty else pd.DataFrame()
        br = br.merge(tot, on='year', how='left')
        branch_cols = list(BRANCH_LABELS)
        for col in branch_cols:
            if col not in br.columns:
                br[col] = 0.0
        br[branch_cols] = br[branch_cols].fillna(0)
        detailed = br[br['year'].ge(2022)]
        totals_by_branch = detailed[branch_cols].sum().sort_values(ascending=False)
        yearly_shares = detailed[branch_cols].div(detailed['нежильё'].replace(0, float('nan')), axis=0)
        over_ten_percent = yearly_shares.gt(0.1).any(axis=0)
        leading = set(totals_by_branch.head(6).index)
        selected = [col for col in branch_cols if col in leading or over_ten_percent[col]]
        selected_sum = br[selected].sum(axis=1)
        scale = (br['нежильё'].fillna(0) / selected_sum.replace(0, float('nan'))).clip(upper=1).fillna(1)
        br[selected] = br[selected].mul(scale, axis=0)
        br['прочее'] = (br['нежильё'].fillna(0) - br[selected].sum(axis=1)).clip(lower=0)
        series3 = [(col, BRANCH_LABELS[col], BRANCH_COLORS[branch_cols.index(col)]) for col in selected]
        series3.append(('прочее', 'Прочее / без детализации', BRANCH_COLORS[-1]))
        append_chart(charts, br, series3, year_from=YF, year_to=YT, key='b3_3', height=300)
        for y0, y1 in [(2011, 2025), (2011, 2026)]:
            lines = '\n'.join((f'- {BRANCH_LABELS[col]}: {ru_num(_sum_range(br, col, y0, y1))} млн м²' for col in selected))
    return charts
