import { useEffect, useMemo } from 'react';
import { ChevronRight, Database } from 'lucide-react';
import { Chart } from './Chart';
import { date, number } from './format';
import { CommissioningEmpty, CommissioningEvidence, CommissioningState, CommissioningTable } from './Operational';
import type { CommissioningChange } from './Operational';
import { MarketExport } from './Annual';
import { permitChartOption, salesTable, tableRows } from './annualConstructionData';
import type { Cell } from './commissioningData';
import { useAnnualConstructionData } from './useAnnualConstructionData';
import type { EChartsCoreOption } from 'echarts/core';
import type { Theme } from './types';

const months = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'];
export const constructionMonthLabel = (m: number) => m === 1 ? months[0] : `Январь–${months[m - 1].toLocaleLowerCase('ru')}`;
const numeric = (v: Cell | undefined) => typeof v === 'number' ? v : null;
const millions = (v: Cell | undefined) => typeof v === 'number' ? v / 1000 : null;
function Metric({ label, value, unit, digits = 2 }: { label: string; value: number | null; unit: string; digits?: number }) { return <div className="metric"><span className="metric-label">{label}</span><div className="metric-number">{number(value, digits)}<span>{unit}</span></div></div>; }
export function constructionSalesOption(label: string, pct: number, color: string, theme: Theme): EChartsCoreOption {
  return { tooltip: { trigger: 'item', confine: true, className: 'commissioning-tooltip', formatter: (p: { name: string; value: number }) => `${p.name}<br/>${number(p.value)} %` }, graphic: [{ type: 'text', left: 'center', top: '43%', style: { text: `${number(pct)} %`, font: '600 22px Segoe UI', fill: theme === 'light' ? '#222831' : '#f0f2f5' } }], series: [{ type: 'pie', name: label, radius: ['65%', '86%'], center: ['50%', '50%'], label: { show: false }, data: [{ name: label, value: pct, itemStyle: { color } }, { name: 'Остальное', value: Math.max(0, 100 - pct), itemStyle: { color: theme === 'light' ? '#dce2e7' : '#40464d' } }] }] };
}
function ConstructionPermits({ theme, params, change }: { theme: Theme; params: URLSearchParams; change: CommissioningChange }) {
  const { catalog, selection, data, error, retry } = useAnnualConstructionData('construction', params);
  useEffect(() => {
    if (!selection) return;
    const repairs = Object.fromEntries(Object.entries({ permit_kind: selection.permitKind, month: String(selection.month) }).filter(([key, value]) => params.get(key) !== value));
    if (Object.keys(repairs).length) change(repairs, true);
  }, [selection?.permitKind, selection?.month, params]);
  return <section className="section construction-permits"><div className="section-heading"><div><h2>Разрешения на строительство · Москва</h2><p>{data?.permits.periodLabel ?? 'Загрузка периода'} · тыс. м²</p></div>{data && selection && <MarketExport kind="construction" selection={selection} version={data.version} />}</div>
    {catalog && selection && <div className="filters commissioning-filters chart-scope-filters"><label><span>Назначение</span><select aria-label="Назначение" value={selection.permitKind} onChange={e => change({ permit_kind: e.target.value })}>{catalog.permitKinds.map(kind => <option key={kind.id} value={kind.id}>{kind.label}</option>)}</select></label><label><span>Период с начала года</span><select aria-label="Период с начала года" value={selection.month} onChange={e => change({ month: e.target.value })}>{catalog.monthsByKind[selection.permitKind].map(month => <option key={month} value={month}>{constructionMonthLabel(month)}</option>)}</select></label></div>}
    {error || !data ? <CommissioningState error={error} retry={retry} catalog={!!catalog} caption="Разрешения на строительство" /> : data.permits.chart?.x.length ? <Chart key={`${data.version}-${selection?.permitKind}-${selection?.month}`} theme={theme} label={data.permits.title} height={400} option={permitChartOption(data.permits, theme)} rows={tableRows(data.permits)} filename={`construction-permits-${selection?.permitKind}-m${selection?.month}`} /> : <CommissioningEmpty text="Нет данных о выдаче разрешений." />}
  </section>;
}
export default function Construction({ theme, query, change }: { theme: Theme; query: string; change: CommissioningChange }) {
  const params = useMemo(() => new URLSearchParams(query), [query]), regionParams = useMemo(() => new URLSearchParams(params.has('region') ? { region: params.get('region')! } : {}), [params]), { catalog, selection, data, error, retry } = useAnnualConstructionData('construction', regionParams), metadata = data ?? catalog;
  useEffect(() => { if (!selection) return; const values = Object.fromEntries(Object.entries({ region: selection.region }).filter(([key, value]) => params.get(key) !== value)); if (Object.keys(values).length) change(values, true); }, [selection?.region, selection?.permitKind, selection?.month, params]);
  const filename = selection ? `construction-${selection.region}-${selection.permitKind}-m${selection.month}` : 'construction', sales = data?.sales;
  return <main className="commissioning-page construction-page" id="construction-page"><div className="page-heading"><div><div className="eyebrow">АНАЛИТИКА НЕДВИЖИМОСТИ</div><h1>Текущее строительство</h1></div><div className="snapshot-label"><Database size={14} />Данные API<span>Дата файлов-кандидатов: {metadata ? date(metadata.source.date) : '—'}</span></div></div>
{catalog && selection && <><div className="filters commissioning-filters"><label><span>Регион показателей</span><select aria-label="Регион показателей" value={selection.region} onChange={e => change({ region: e.target.value })}>{catalog.regions.map(r => <option key={r.id} value={r.id}>{r.label}</option>)}</select></label><a className="source-anchor" href="#construction-sources"><Database size={15} />Источники<ChevronRight size={14} /></a></div></>}
    {error || !catalog || selection && !data ? <CommissioningState error={error} retry={retry} catalog={!!catalog} caption="Текущее строительство" /> : !selection ? <CommissioningEmpty text="Нет доступных фильтров." /> : data && <><div className="developer-heading commissioning-heading"><div className="developer-name"><h2>{catalog.regions.find(r => r.id === selection.region)?.label}</h2></div></div>
      <section className="section construction-volumes"><div className="section-heading"><div><h2>Объём текущего строительства</h2><p>{data.constructionPeriod || 'Период источника не указан'}</p></div></div><div className="kpi-band construction-area-metrics">{data.metrics.filter(m => m.id === 'living' || m.id === 'total').map(m => <Metric key={m.id} {...m} />)}</div></section>
      <section className="section"><div className="section-heading"><div><h2>Распроданность и стройготовность</h2><p>{data.salesReadinessPeriod ? `${months[data.salesReadinessPeriod.month - 1]} ${data.salesReadinessPeriod.year}` : 'Период источника не указан'}</p></div></div><div className="kpi-band construction-sales-metrics">{data.metrics.filter(m => m.id !== 'living' && m.id !== 'total').map(m => <Metric key={m.id} {...m} />)}</div></section>
      <section className="section"><div className="section-heading"><div><h2>Реализация квартир</h2><p>{sales && typeof sales.report_period === 'string' ? sales.report_period : 'Период источника не указан'}</p></div></div>{sales ? <><div className="kpi-band construction-area-metrics"><Metric label="Всего жилой площади" value={millions(sales.total_living_thousand_m2)} unit="млн м²" /><Metric label="Продажи открыты" value={millions(sales.sales_open_thousand_m2)} unit="млн м²" /></div><div className="construction-donuts">{[{ key: 'sold', label: 'Проданная площадь', color: '#2c9869' }, { key: 'unsold', label: 'Непроданная площадь', color: '#398dcc' }, { key: 'sales_not_open', label: 'Продажи не открыты', color: theme === 'light' ? '#6f8091' : '#96a7b8' }].map(s => { const pct = numeric(sales[`${s.key}_pct`]), area = millions(sales[`${s.key}_thousand_m2`]); return <div key={s.key}><h3>{s.label}</h3>{pct !== null && pct >= 0 ? <Chart key={`${data.version}-${selection.region}-${s.key}`} theme={theme} label={s.label} option={constructionSalesOption(s.label, pct, s.color, theme)} height={210} rows={[["Показатель", "Доля, %", "Площадь, тыс. м²"], [s.label, pct, sales[`${s.key}_thousand_m2`] ?? null]]} filename={`${filename}-${s.key}`} /> : <CommissioningEmpty text="Доля в источнике не указана." />}<p className="construction-donut-value">{number(area, 2)} млн м²{pct !== null && pct < 0 && <span> · {number(pct)} % в источнике</span>}</p></div>; })}</div><div className="kpi-band construction-area-metrics"><Metric label="Стоимость 1 м²" value={numeric(sales.price_per_m2_rub)} unit="руб." digits={0} /><Metric label="Объём привлечённых средств" value={numeric(sales.funds_million_rub)} unit="млн руб." digits={0} /></div><CommissioningTable table={salesTable(sales)} params={params} change={change} scope="constructionSales" filename={`${filename}-sales-raw`} /></> : <CommissioningEmpty text="Детальные данные о реализации отсутствуют в источнике." />}</section>
<ConstructionPermits theme={theme} params={params} change={change} />
      <section className="section"><p className="method-note">Оперативный источник: {data.sourceDetails.file ?? 'Файл не указан'} · {date(data.sourceDetails.date)}</p></section>
    </>}{metadata && <CommissioningEvidence metadata={metadata} anchor="construction-sources" notes={data?.notes} />}<footer className="page-footer"><span>Аналитика Москвы</span><span>Текущее строительство · API</span></footer></main>;
}
