import { useEffect, useMemo } from 'react';
import { AlertCircle, ChevronRight, Database } from 'lucide-react';
import { Chart } from './Chart';
import { date, number } from './format';
import { commissioningParams, linearDigits, linearSummaryOption, linearTable, linearTrendOption, tableRows } from './commissioningData';
import type { Cell } from './commissioningData';
import { CommissioningEmpty, CommissioningEvidence, CommissioningExport, CommissioningState, CommissioningTable, QuarterControls, periodCaption } from './Operational';
import type { CommissioningChange } from './Operational';
import { useCommissioningData } from './useCommissioningData';
import type { Theme } from './types';

function linearCell(value: Cell, column: string, row: Record<string, Cell>) { return typeof value === 'number' ? number(value, column === 'percent' ? 1 : column === 'plan' || column === 'fact' ? linearDigits(String(row.unit)) : 0) : value ?? '—'; }
export default function Linear({ theme, query, change }: { theme: Theme; query: string; change: CommissioningChange }) {
  const params = useMemo(() => new URLSearchParams(query), [query]);
  const { catalog, selection, data, error, retry } = useCommissioningData('linear', params);
  useEffect(() => { if (!selection) return; const values = Object.fromEntries(Object.entries(commissioningParams(selection)).filter(([key, value]) => params.get(key) !== value)); if (Object.keys(values).length) change(values, true); }, [selection?.year, selection?.quarter, selection?.cumulative, selection?.indicator, params]);
  const metadata = data ?? catalog, year = catalog?.years.find(y => y.id === String(selection?.year)), indicator = catalog?.indicators.find(i => i.id === selection?.indicator);
  const filename = selection ? `linear-${selection.year}-q${selection.quarter}-${selection.cumulative ? 'ytd' : 'quarter'}` : 'linear';
  return <main className="commissioning-page linear-page" id="linear-page"><div className="page-heading"><div><div className="eyebrow">АНАЛИТИКА НЕДВИЖИМОСТИ</div><h1>Ввод линейных объектов</h1></div><div className="snapshot-label"><Database size={14} />Данные API<span>Дата отчёта: {metadata ? date(metadata.source.date) : '—'}</span></div></div>
    {catalog && selection && year && <><div className="filters commissioning-filters"><QuarterControls years={catalog.years} quarters={year.quarters} year={selection.year} quarter={selection.quarter} cumulative={selection.cumulative} change={change} resetQuarterOnYearChange /><a className="source-anchor" href="#linear-sources"><Database size={15} />Источники<ChevronRight size={14} /></a></div></>}
    {error || !catalog || selection && !data ? <CommissioningState error={error} retry={retry} catalog={!!catalog} caption="Ввод линейных объектов" /> : !selection ? <CommissioningEmpty text="Нет доступных периодов или показателей." /> : data && <><div className="developer-heading commissioning-heading"><div className="developer-name"><h2>План и факт</h2><span className="region-label">{periodCaption(data.selection.year, data.selection.quarter, data.selection.cumulative)}</span></div><CommissioningExport kind="linear" selection={data.selection} version={data.version} /></div>{data.summary.some(r => r.fact === null) && <p className="method-note warning-text linear-missing-fact"><AlertCircle size={14} /><span>Для выбранного периода факт ещё не указан в отчёте. Пустые значения не считаются нулём.</span></p>}
      <section className="section linear-summary" aria-label="План и факт по показателям"><div className="linear-summary-grid">{data.summary.map(row => <div className="linear-indicator" key={row.code} data-indicator={row.code}><h3>{row.indicator}</h3><div className="linear-metrics">{[{ label: 'План', value: row.plan, unit: row.unit, digits: linearDigits(row.unit) }, { label: 'Факт', value: row.fact, unit: row.unit, digits: linearDigits(row.unit) }, { label: 'Выполнение плана', value: row.percent, unit: '%', digits: 1 }].map(m => <div className="metric" key={m.label}><span className="metric-label">{m.label}</span><div className="metric-number">{number(m.value, m.digits)}<span>{m.unit}</span></div></div>)}</div>{row.plan !== null || row.fact !== null ? <Chart key={`${data.version}-${JSON.stringify(data.selection)}-${row.code}`} theme={theme} option={linearSummaryOption(row, theme)} label={`План и факт: ${row.indicator}`} height={180} rows={tableRows(linearTable([row], row.indicator))} filename={`${filename}-${row.code}`} /> : <CommissioningEmpty />}</div>)}</div>{!data.summary.length && <CommissioningEmpty />}</section>
      <section className="section linear-trend" aria-label="Динамика по кварталам"><div className="section-heading"><div><h2>Динамика по кварталам</h2><p>{indicator?.label ?? selection.indicator} · {selection.year} · {selection.cumulative ? 'с начала года' : 'за квартал'} · {indicator?.unit}</p></div></div><div className="filters commissioning-indicator-filter"><label><span>Показатель динамики</span><select aria-label="Показатель динамики" value={selection.indicator} onChange={e => change({ indicator: e.target.value })}>{catalog.indicators.map(i => <option key={i.id} value={i.id}>{i.label} · {i.unit}</option>)}</select></label></div>{data.trend.some(r => r.plan !== null || r.fact !== null) ? <Chart key={`${data.version}-${JSON.stringify(data.selection)}-trend`} theme={theme} option={linearTrendOption(data.trend, indicator?.unit ?? data.trend[0]?.unit ?? '', theme)} label={`Динамика по кварталам: ${indicator?.label ?? selection.indicator}`} height={320} rows={tableRows(linearTable(data.trend))} filename={`${filename}-${selection.indicator}-trend`} /> : <CommissioningEmpty />}</section>
      <section className="section linear-all-periods"><CommissioningTable table={linearTable(data.allPeriods)} params={params} change={change} scope="linearAll" filename={`${filename}-all-periods`} cellText={linearCell} /></section>
    </>}
    {metadata && <CommissioningEvidence metadata={metadata} anchor="linear-sources" />}<footer className="page-footer"><span>Аналитика Москвы</span><span>Ввод линейных объектов · API</span></footer></main>;
}
