import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, ChevronLeft, ChevronRight, Database, Download, FileSpreadsheet, RefreshCw, Search } from 'lucide-react';
import { Chart } from './Chart';
import { ApiError, request } from './data';
import { date, exportCsv, number } from './format';
import { commissioningParams, commissioningUrl, groupedStructure, operationalChartOption, operationalChartRows, reportTablePage, structureRows, tableRows } from './commissioningData';
import type { Cell, CommissioningKind, CommissioningMetadata, CommissioningSelection, OperationalReport, ReportTable } from './commissioningData';
import { useCommissioningData } from './useCommissioningData';
import type { Theme } from './types';

export type CommissioningChange = (values: Record<string, string | null>, replace?: boolean) => void;
export function CommissioningEmpty({ text = 'Нет данных.' }: { text?: string }) { return <div className="empty-state"><Database size={20} /><span>{text}</span></div>; }
export function CommissioningState({ error, retry, catalog, caption }: { error: string; retry: () => void; catalog: boolean; caption: string }) {
  return error ? <div className="load-state" role="alert"><AlertCircle size={26} /><h2>{caption} API недоступен</h2><p>{error}</p><button onClick={retry}><RefreshCw size={15} />Повторить</button></div> : <div className="load-state" role="status" aria-live="polite"><RefreshCw className="loading-icon" size={26} /><p>{catalog ? 'Загрузка отчёта…' : 'Загрузка каталога…'}</p></div>;
}
export function CommissioningExport({ kind, selection, version }: { kind: CommissioningKind; selection: CommissioningSelection; version: string }) {
  const active = useRef<AbortController>(), scope = JSON.stringify([kind, selection, version]);
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { setBusy(false); setError(''); return () => active.current?.abort(); }, [scope]);
  async function download() {
    active.current?.abort(); const controller = new AbortController(); active.current = controller;
    setBusy(true); setError('');
    try {
      const blob = await (await request(commissioningUrl(kind, selection, version), controller.signal)).blob();
      if (controller.signal.aborted) return;
      const url = URL.createObjectURL(blob), link = document.createElement('a');
      link.href = url; link.download = `${kind}-${selection.year}-q${selection.quarter}.xlsx`;
      document.body.append(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (e) {
      if (!controller.signal.aborted) setError(e instanceof ApiError && e.status === 409 ? 'Данные изменились. Перезагрузите страницу, затем скачайте Excel.' : `${e instanceof Error ? e.message : 'Не удалось скачать Excel.'} Повторите скачивание.`);
    } finally { if (!controller.signal.aborted) setBusy(false); }
  }
  const caption = kind === 'operational' ? 'Скачать оперативный ввод Excel' : 'Скачать линейные объекты Excel';
  return <div className="profile-export commissioning-export"><button className="icon-button" title={caption} aria-label={caption} disabled={busy} onClick={download}>{busy ? <RefreshCw size={17} className="loading-icon" /> : <FileSpreadsheet size={17} />}</button>{error && <span role="alert" className="warning-text">{error}</span>}</div>;
}
export function CommissioningEvidence({ metadata, anchor, notes = [], detail }: { metadata: CommissioningMetadata; anchor: string; notes?: string[]; detail?: OperationalReport['sourceDetails'] }) {
  const candidates = metadata.source.fileEvidence === 'candidates';
  return <section className="section sources-section" id={anchor}><div className="section-heading"><h2>Источники и даты</h2><Database size={17} /></div><p className="muted">{candidates ? 'Дата файлов-кандидатов' : 'Дата отчёта'}: {date(metadata.source.date)}</p>{metadata.source.issues.map(([level, text], i) => <p className="method-note warning-text" key={i}><AlertCircle size={14} /><span>{level}: {text}</span></p>)}{notes.map((text, i) => <p key={i} className="method-note">{text}</p>)}<details><summary>Метаданные источника</summary><p className="muted">Дата формирования: {date(metadata.generatedAt)} · версия: {metadata.version}</p>{metadata.source.dateEvidence && <p className="muted">{metadata.source.dateEvidence}</p>}<div className="source-list"><div><strong>{candidates ? 'Файлы-кандидаты' : 'Выбранный файл отчёта'}</strong><span>{date(metadata.source.date)}</span><div>{metadata.source.files.map((file, i) => <code key={i}>{file}</code>)}{candidates && <p>Кандидаты источника, не журнал прочитанных файлов.</p>}</div></div>{detail && <div><strong>Источник месячной истории</strong><span>{date(detail.date)}</span><div><code>{detail.file ?? 'Файл не указан'}</code></div></div>}</div></details></section>;
}
export function QuarterControls({ years, quarters, year, quarter, cumulative, change, resetQuarterOnYearChange = false }: { years: { id: string; label: string }[]; quarters: number[]; year: number; quarter: number; cumulative: boolean; change: CommissioningChange; resetQuarterOnYearChange?: boolean }) {
  return <><label><span>Год</span><select aria-label="Год" value={year} onChange={e => change({ year: e.target.value, ...(resetQuarterOnYearChange ? { quarter: null } : {}) })}>{years.map(y => <option key={y.id} value={y.id}>{y.label}</option>)}</select></label><label><span>Квартал</span><select aria-label="Квартал" value={quarter} onChange={e => change({ quarter: e.target.value })}>{quarters.map(q => <option key={q} value={q}>{q} квартал</option>)}</select></label><fieldset className="commissioning-mode"><legend>Расчёт периода</legend>{[{ value: false, label: 'За квартал' }, { value: true, label: 'С начала года' }].map(mode => <label key={String(mode.value)}><input type="radio" name="commissioning-mode" checked={cumulative === mode.value} onChange={() => change({ cumulative: String(mode.value) })} /><span>{mode.label}</span></label>)}</fieldset></>;
}
export function CommissioningTable({ table, params, change, scope, filename, cellText }: { table: ReportTable; params: URLSearchParams; change: CommissioningChange; scope: string; filename: string; cellText?: (value: Cell, column: string, row: Record<string, Cell>) => string }) {
  const searchKey = `${scope}Search`, pageKey = `${scope}Page`, sizeKey = `${scope}Size`, query = params.get(searchKey) ?? '';
  const view = reportTablePage(table, query, params.get(pageKey), params.get(sizeKey));
  useEffect(() => {
    const values: Record<string, string> = {};
    if (params.has(pageKey) && params.get(pageKey) !== String(view.current)) values[pageKey] = String(view.current);
    if (params.has(sizeKey) && params.get(sizeKey) !== String(view.pageSize)) values[sizeKey] = String(view.pageSize);
    if (Object.keys(values).length) change(values, true);
  }, [params, pageKey, sizeKey, view.current, view.pageSize]);
  return <div className="commissioning-table" aria-label={table.title}><div className="section-heading commissioning-table-heading"><div><h3>{table.title}</h3><p>{number(table.rows.length)} строк</p></div><button className="icon-button" title={`Скачать все строки CSV: ${table.title}`} aria-label={`Скачать все строки CSV: ${table.title}`} onClick={() => exportCsv(tableRows(table), `${filename}.csv`)}><Download size={17} /></button></div><div className="object-toolbar"><label className="object-search"><Search size={14} /><input type="search" aria-label={`Поиск: ${table.title}`} placeholder="Поиск" value={query} onChange={e => change({ [searchKey]: e.target.value || null, [pageKey]: null })} /></label><label className="apartment-page-size"><span>Строк</span><select aria-label={`Строк на странице: ${table.title}`} value={view.pageSize} onChange={e => change({ [sizeKey]: e.target.value, [pageKey]: null })}>{[20, 50, 100].map(size => <option key={size}>{size}</option>)}</select></label></div><div className="table-wrap" tabIndex={0} role="region" aria-label={`Таблица: ${table.title}`}><table><thead><tr>{table.columns.map(c => <th scope="col" key={c.id}>{c.label}</th>)}</tr></thead><tbody>{view.shown.map((r, i) => <tr key={i}>{table.columns.map((c, j) => { const value = r[c.id], text = cellText ? cellText(value, c.id, r) : typeof value === 'number' ? value.toLocaleString('ru-RU', { maximumFractionDigits: 20 }) : value ?? '—'; return j === 0 ? <th scope="row" key={c.id}>{text}</th> : <td key={c.id}>{text}</td>; })}</tr>)}</tbody></table></div>{!view.shown.length && <CommissioningEmpty text={table.rows.length ? 'Ничего не найдено.' : 'Нет данных для выбранного периода.'} />}<div className="pagination"><span aria-live="polite">{number(view.total)} строк · страница {view.current} из {view.pages}</span><button className="icon-button" title={`Предыдущая страница: ${table.title}`} aria-label={`Предыдущая страница: ${table.title}`} disabled={view.current === 1} onClick={() => change({ [pageKey]: String(view.current - 1) })}><ChevronLeft size={15} /></button><button className="icon-button" title={`Следующая страница: ${table.title}`} aria-label={`Следующая страница: ${table.title}`} disabled={view.current === view.pages} onClick={() => change({ [pageKey]: String(view.current + 1) })}><ChevronRight size={15} /></button></div></div>;
}
export function periodCaption(year: number, quarter: number, cumulative: boolean) { return `${cumulative && quarter > 1 ? `1–${quarter} кварталы` : `${quarter} квартал`} ${year}`; }
function operationalCell(value: Cell, column: string) { return typeof value === 'number' ? number(value, column === 'Год' ? 0 : column.includes('%') ? 1 : 2) : value ?? '—'; }
export default function Operational({ theme, query, change }: { theme: Theme; query: string; change: CommissioningChange }) {
  const params = useMemo(() => new URLSearchParams(query), [query]);
  const { catalog, selection, data, error, retry } = useCommissioningData('operational', params);
  useEffect(() => { if (!selection) return; const values = Object.fromEntries(Object.entries(commissioningParams(selection)).filter(([key, value]) => params.get(key) !== value)); if (Object.keys(values).length) change(values, true); }, [selection?.month, selection?.excludeMkd, selection?.year, selection?.quarter, selection?.cumulative, params]);
  const metadata = data ?? catalog, filename = selection ? `operational-${selection.year}-m${selection.month}-q${selection.quarter}-${selection.cumulative ? 'ytd' : 'quarter'}-${selection.excludeMkd ? 'standalone' : 'all'}` : 'operational';
  return <main className="commissioning-page operational-page" id="operational-page"><div className="page-heading"><div><div className="eyebrow">АНАЛИТИКА НЕДВИЖИМОСТИ</div><h1>Ввод недвижимости · оперативные данные</h1></div><div className="snapshot-label"><Database size={14} />Данные API<span>Дата файлов-кандидатов: {metadata ? date(metadata.source.date) : '—'}</span></div></div>
    {catalog && selection && <><div className="filters commissioning-filters"><label className="commissioning-month"><span>Период с начала года</span><select aria-label="Период с начала года" value={selection.month} onChange={e => change({ month: e.target.value })}>{catalog.months.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}</select></label><span className="region-label">Москва · {catalog.currentYear}</span><a className="source-anchor" href="#operational-sources"><Database size={15} />Источники<ChevronRight size={14} /></a></div><label className="commissioning-checkbox operational-exclusion"><input type="checkbox" aria-label="Без нежилых помещений в жилых объектах" checked={selection.excludeMkd} onChange={e => change({ exclude_mkd: String(e.target.checked) })} /><span>Без нежилых помещений в жилых объектах</span></label><fieldset className="commissioning-quarter-scope"><legend>Квартальная структура ввода</legend><div className="filters commissioning-filters quarter-filters"><QuarterControls years={catalog.years.map(y => ({ id: String(y), label: String(y) }))} quarters={[1, 2, 3, 4]} year={selection.year} quarter={selection.quarter} cumulative={selection.cumulative} change={change} /></div></fieldset></>}
    {error || !catalog || selection && !data ? <CommissioningState error={error} retry={retry} catalog={!!catalog} caption="Оперативный ввод" /> : !selection ? <CommissioningEmpty text="Нет доступных периодов." /> : data && <><div className="developer-heading commissioning-heading"><div className="developer-name"><h2>{data.region}</h2><span className="region-label">{data.periodLabel} · {data.currentYear}</span></div><CommissioningExport kind="operational" selection={data.selection} version={data.version} /></div>
      {data.tables.map(t => <section className="section operational-series" key={t.id} aria-label={t.title}><div className="section-heading"><div><h2>{t.title}</h2><p>{data.region} · млн м² · {data.periodLabel}{t.id === 'nonres' ? ` · ${selection.excludeMkd ? 'без нежилых помещений в жилых объектах' : 'всё нежильё'}` : ''}</p></div></div>{t.chart.x.length ? <Chart key={`${data.version}-${JSON.stringify(data.selection)}-${t.id}`} theme={theme} label={t.title} option={operationalChartOption(t, data.periodLabel, theme)} height={380} rows={operationalChartRows(t)} filename={`${filename}-${t.id}-chart`} /> : <CommissioningEmpty />}<CommissioningTable table={t} params={params} change={change} scope={`operational${t.id}`} filename={`${filename}-${t.id}`} cellText={operationalCell} /></section>)}
      <section className="section operational-structure"><div className="section-heading"><div><h2>Структура ввода за квартал</h2><p>{data.region} · {periodCaption(selection.year, selection.quarter, selection.cumulative)} · млн м²</p></div><button className="icon-button" title="Скачать структуру ввода CSV" aria-label="Скачать структуру ввода CSV" onClick={() => exportCsv(structureRows(data.treeRows), `${filename}-structure.csv`)}><Download size={17} /></button></div><div className="operational-structure-grid">{groupedStructure(data.treeRows).map(group => <div key={group.title} className="operational-structure-group"><h3>{group.title}</h3><dl>{group.rows.map(r => <div key={r.id} data-structure-id={r.id}><dt>{r.label}</dt><dd>{number(r.value, 2)}<span>млн м²</span></dd></div>)}</dl></div>)}</div>{!data.treeRows.length && <CommissioningEmpty />}</section>
    </>}
    {metadata && <CommissioningEvidence metadata={metadata} anchor="operational-sources" notes={data?.notes} detail={data?.sourceDetails} />}<footer className="page-footer"><span>Аналитика Москвы</span><span>Оперативный ввод · API</span></footer></main>;
}
