"""Mechanically extract pandas calculations from the approved annual page.

Run only when updating the shared module, then verify against original-page
execution. No runtime source execution and no changes to the original page.
"""
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "app/pages/8_Ввод_недвижимости.py"
TARGET = ROOT / "pipeline/annual_calculations.py"
LOADERS = ("load_vvod_static", "load_emiss_34118", "load_emiss_34118_periods",
           "load_monitoring_2_0", "load_monitoring_2011_2026_static")


def ui_call(node):
    return isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name) and node.func.value.id == "st"


class Extract(ast.NodeTransformer):
    def visit_Call(self, node):
        node = self.generic_visit(node)
        if isinstance(node.func, ast.Name) and node.func.id in LOADERS:
            return ast.Subscript(value=ast.Name(id="data", ctx=ast.Load()),
                                 slice=ast.Constant(node.func.id), ctx=ast.Load())
        if isinstance(node.func, ast.Name) and node.func.id == "render_stacked":
            node.func.id = "append_chart"
            node.args.insert(0, ast.Name(id="charts", ctx=ast.Load()))
        return node

    def visit_Expr(self, node):
        if ui_call(node.value):
            if node.value.func.attr == "stop":
                return ast.Return(value=ast.Name(id="charts", ctx=ast.Load()))
            return None
        if isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name) and node.value.func.id in ("apply_theme", "page_header"):
            return None
        return self.generic_visit(node)

    def visit_Assign(self, node):
        if ui_call(node.value):
            return None
        return self.generic_visit(node)

    def visit_With(self, node):
        result = []
        for child in node.body:
            visited = self.visit(child)
            if isinstance(visited, list):
                result.extend(visited)
            elif visited is not None:
                result.append(visited)
        return result

    def visit_If(self, node):
        node = self.generic_visit(node)
        return node if node.body else None

    def visit_For(self, node):
        node = self.generic_visit(node)
        return node if node.body else None


def main():
    tree = ast.parse(SOURCE.read_text(encoding="utf-8"))
    helpers, body, constants = [], [], []
    in_body = False
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            if node.name.startswith("_") or node.name == "ru_num":
                helpers.append(node)
        elif isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "vvod" for t in node.targets):
            in_body = True
            body.append(node)
        elif in_body:
            body.append(node)
        elif isinstance(node, ast.Assign):
            constants.append(node)
    transformed = Extract().visit(ast.Module(body=body, type_ignores=[])).body
    function = ast.parse("def annual_charts(data, region):\n    charts = []\n").body[0]
    function.body.extend(transformed)
    function.body.append(ast.Return(value=ast.Name(id="charts", ctx=ast.Load())))
    generated = ast.fix_missing_locations(ast.Module(body=constants + helpers + [function], type_ignores=[]))
    header = '''"""Annual commissioning calculations mechanically extracted from the legacy page.

Generated by scripts/extract_annual_calculations.py; verify against original
page execution after updating. Zero filling and historical overrides are the
legacy rules, not additional claims of source completeness.
"""
import pandas as pd
from pipeline.data_access import monitoring_by_year, month_label, quarter_label
from pipeline.report_values import records

COLORS = {"green": "#2c9869", "amber": "#d6a23f", "blue": "#398dcc", "teal": "#329d9c"}

TITLES = {"b1": "Ввод недвижимости", "b2_1": "МКД и ИЖС",
          "b2_2": "Бюджетное и небюджетное жильё · Москва", "b2_3": "Реновация · Москва",
          "b3_1": "Нежильё и нежилые помещения в жилье · Москва",
          "b3_2": "Бюджетное и небюджетное нежильё · Москва", "b3_3": "Нежильё по отраслям · Москва"}

def append_chart(charts, frame, series, *, year_from, year_to, key, totals=True, height=360):
    years = list(range(year_from, year_to + 1))
    if frame is None or frame.empty:
        shown = pd.DataFrame({"year": years})
    else:
        shown = frame.set_index("year").reindex(years).reset_index()
    for column, _, _ in series:
        if column not in shown.columns:
            shown[column] = 0.0
    shown = shown.fillna(0.0)
    columns = ["year"] + [column for column, _, _ in series]
    charts.append({"id": key, "title": TITLES[key], "unit": "млн м²", "totals": totals,
                   "columns": [{"id": "year", "label": "Год"}] + [{"id": col, "label": label} for col, label, _ in series],
                   "rows": records(shown[columns]),
                   "series": [{"id": col, "name": label, "color": color,
                               "points": [{"x": str(int(row["year"])), "y": row[col]} for row in records(shown[columns])]}
                              for col, label, color in series],
                   "summaries": [{"from": year_from, "to": end,
                                  "values": [{"id": col, "label": label, "value": _sum_range(frame, col, year_from, end)}
                                             for col, label, _ in series]}
                                 for end in (2025, 2026)]})

'''
    TARGET.write_text(header + ast.unparse(generated) + "\n", encoding="utf-8")
    compile(TARGET.read_text(encoding="utf-8"), str(TARGET), "exec")


if __name__ == "__main__":
    main()
