[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#E84C4C"
backgroundColor = "#0C141D"
secondaryBackgroundColor = "#1A2634"
textColor = "#E8EEF4"
font = "sans serif"
